### ISSUE TITLE
[barquero] Complex Event Processing

### ISSUE THREAD

**Issue by grammarware** [modelsconf2018/artifact-evaluation#15]
Submitted by @lolybc88 to https://github.com/modelsconf2018/artifact-evaluation/tree/master/barquero

Paper: http://www.lcc.uma.es/%7Eloli/downloads/MODELS18_2.pdf

**Comment by zolotas4** [comment]
Hi,

1) I was able to run in test/development mode the first example (motornikeProject) but when I export the jar and try to run I receive the following exception: 

`Caused by: java.io.FileNotFoundException: class path resource [application-context.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:329)`

Both the config.properties and the motorbike.csv files are in the same directory as the jar. 

2) I was not able to run in test/development mode for 2 and 3 examples (I haven't tried the 4th). I set the Scala compiler version to 2.11 as suggested, I then try to follow the Maven dependencies build as suggested but although Run As ... -> Maven Clean executes successfully, I receive the following Build Failure message when I do Run As ... -> Maven Install

`[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.cor.motorbike:motorbike4Graphx:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 63, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building graphframes 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://scala-tools.org/repo-releases/org/scala-tools/maven-scala-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.scala-tools:maven-scala-plugin/maven-metadata.xml from/to scala-tools.org (http://scala-tools.org/repo-releases): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: http://scala-tools.org/repo-releases/commons-codec/commons-codec/maven-metadata.xml
[WARNING] Could not transfer metadata commons-codec:commons-codec/maven-metadata.xml from/to scala-tools.org (http://scala-tools.org/repo-releases): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] Downloading: http://scala-tools.org/repo-releases/commons-codec/commons-codec/2.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata commons-codec:commons-codec:2.0-SNAPSHOT/maven-metadata.xml from/to scala-tools.org (http://scala-tools.org/repo-releases): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer commons-codec:commons-codec:2.0-SNAPSHOT/maven-metadata.xml from http://scala-tools.org/repo-releases was cached in the local repository, resolution will not be reattempted until the update interval of scala-tools.org has elapsed or updates are forced. Original error: Could not transfer metadata commons-codec:commons-codec:2.0-SNAPSHOT/maven-metadata.xml from/to scala-tools.org (http://scala-tools.org/repo-releases): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ motorbike4Graphx ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/Thanos/Downloads/AEModels/graphCEP-master/motorbike4Graphx/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ motorbike4Graphx ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ motorbike4Graphx ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  com.cor.motorbike:motorbike4Graphx:0.0.1-SNAPSHOT requires scala version: 2.11.12
[WARNING]  com.twitter:chill_2.11:0.8.4 requires scala version: 2.11.8
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] /Users/Thanos/Downloads/AEModels/graphCEP-master/motorbike4Graphx/src/main/java:-1: info: compiling
[INFO] Compiling 14 source files to /Users/Thanos/Downloads/AEModels/graphCEP-master/motorbike4Graphx/target/classes at 1531817465829
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] /Users/Thanos/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar: invalid LOC header (bad signature)
[INFO] java.lang.reflect.InvocationTargetException
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.NoClassDefFoundError: scala/collection/mutable/IndexedSeq
[INFO] 	at scala.util.PropertiesTrait$class.$init$(Properties.scala:31)
[INFO] 	at scala.tools.nsc.Properties$.<init>(Properties.scala:12)
[INFO] 	at scala.tools.nsc.Properties$.<clinit>(Properties.scala)
[INFO] 	at scala.tools.nsc.Driver.<init>(Driver.scala:10)
[INFO] 	at scala.tools.nsc.MainClass.<init>(Main.scala:13)
[INFO] 	at scala.tools.nsc.Main$.<init>(Main.scala:27)
[INFO] 	at scala.tools.nsc.Main$.<clinit>(Main.scala)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.169 s
[INFO] Finished at: 2018-07-17T09:51:06+01:00
[INFO] Final Memory: 26M/460M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:compile (default) on project motorbike4Graphx: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240(Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`
Any idea?

**Comment by stsauer** [comment]
zolotas4, have you increased the heap size as indicated?

**Comment by zolotas4** [comment]
Yes, I did.

**Comment by lolybc88** [comment]
Hi,
The code was developed by Gala Barquero, I've asked her and this is her reply:
----
1. There is an error in the deployment paragraph of the first example. You should do:
To export a jar file:
Right Click on ‘motorbikeProject’ project and select Run As...->Maven Install.
When Maven Install finishs the jar file will be created in /motorbikeProject/target/.
Note that to run the jar file you have to copy ‘motorbike.csv’ and ‘config.properties’ (of ‘motorbikeProject’ project) files in the same folder as the jar.
Sorry for the inconvenience.

2. That is not a real problem, this step is needed only to force to re-download all dependencies. You can continue with 'Update project' step. So, you can skip the error message.
-----
If the problem persist, could you contact her directly by adding her as collaborator: @Galabarquerom or by email at gala@lcc.uma.es?

Thanks

**Comment by zolotas4** [comment]
Hi @lolybc88 

Thanks but the projects do not compile at all so I am not able to run them. I thought the reason for not compiling would be the fact the maven dependencies were not installed. In any case I sent an email to Gala with the errors I get and we will discuss this offline until @grammarware adds her to the repo.

Cheers,
Thanos

**Comment by grammarware** [comment]
@galabarquerom has been added. Welcome to the discussion!

**Comment by Bitico** [comment]
The paper extends the CEP systems so to permit dealing with graph-structured information. They provide a prototypical solution to validate their solution.

**(1) Is the artifact consistent with the paper?**
All the case studies presented in the paper are reported so the artifact result to be consistent.

**(2) Is the artifact as complete as possible?**
Yes, all the case studies, following the authors instructions, work properly.

**(3) Is the artifact well-documented?**
All the proposed example are well documented (Very fine step-by-step documentation).

**(4) Is the artifact easy to (re)use?**
Yes, the artifact is easy to reuse. A simple main class to invoke to replicate the example and easy to parameterize and configuration file are provided.

**Comment by zolotas4** [comment]
**Summary**
The authors provide artefacts for the implementation of an approach in which complex event processing is done on data that are stored in graph structures which evolve over time.
 
**Is the artefact consistent with the paper?**
Yes, the artefact is consistent with the paper. 

**Is the artefact as complete as possible?**
Yes, the artefact is as complete as possible. All the case studies described in the paper are also provided.

**Is the artefact well-documented?**
The artefact is in general well-documented. There are some small issues that I suggest the authors to fix:
* Give the exact name of the projects that need to be imported (e.g., motorbikeProject). It might be tricky to locate the correct one. 
* The authors mention the "TwitterFlickrStatic" project in case 3 however such a project doesn't exist. I guess they mean the "TwitterUserStatic" project instead.
* Provide information or at least a link to a guide on how to update heap size in Eclipse
* Runnable Jars are not exported the way it is described in the documentation according to the authors. Please remember to update with the correct information. 
* Mention that for Maven projects users need to go to "Import Existing Maven Project" instead of "Import Existing Project" they do for the Java ones.

**Is the artefact easy to (re)use?**
Step-by-step instructions are given which in principle make replication easy. For me it was not straight-forward though. I was never able to make the solution work on my MacOS. I tried several troubleshooting steps suggested by the developers but with no luck. The developers claim that they were able to run this with no problem in at least 3 different Mac OS machines on their own (In one of them they managed to replicate the errors I get however the steps that solved the problem for them didn't work on my machine). I was able to run the solution in my Windows machine with no problem.

In addition:
* For the 2nd use case, sometimes the results I got (for the non delayed version) were (up to 5 times) slower than those reported in the paper. However, my machine is of lower specifications than the one used in the original experiment (16GB Ram & 4 cores vs 64GB RAM & 16 cores). So, this most probably explains the difference.
* For the 3rd case, the results for the 1st configuration were almost identical. I wasn't able to completely run the 2nd configuration experiment as after several minutes I was receiving an out of memory exception, although I had set the max heap size to 10G as suggested by the authors. For the tests ran before the exception was thrown the results were consistent with those presented in the paper. I don't believe that this is a problem to the foundations of the proposed approach and the experiment. 

Otherwise, the examples are very easy to re-use as Java runners are provided.

**Comment by galabarquerom** [comment]
Hi, 
We have modified the README.md file according to your suggestions.
Sorry for the inconvenience and thank you for your patience.
Regards.

**Comment by grammarware** [comment]
Dear @lolybc88 and @galabarquerom,

Based on all the comments and the reviews provided by the members of the Artifact Evaluation Committee of MoDELS 2018, we have reached the conclusion that this artifact conforms to the expectations and is hereby **approved**. Please use the [badge instructions](https://github.com/modelsconf2018/artifact-evaluation/blob/master/Badge.md) page to add the badge of approval to your article, and add the link to the ReMoDD entry with URI http://remodd.org/node/583 to the camera ready version of the paper.

Thank you very much for putting extra effort into the preparation and finalising of the artifact. If any of the comments above are still not addressed, please try to accommodate them before the conference.
