### ISSUE TITLE
[morin] Engineering Software Diversity

### ISSUE THREAD

**Issue by grammarware** [modelsconf2018/artifact-evaluation#5]
Submitted by @brice-morin to https://github.com/modelsconf2018/artifact-evaluation/tree/master/morin

**Comment by moji1** [comment]
Hi @brice-morin
I am trying to build thingml-diversifier cloned from https://github.com/SINTEF-9012/thingml-diversifier, but it fails with the following error, can you please help me to fix that. 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.952 s
[INFO] Finished at: 2018-07-16T12:18:57+04:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project thingml.diversifier: Could not resolve dependencies for project no.sintef:thingml.diversifier:jar:1.0.0-SNAPSHOT: Could not find artifact org.thingml:compilers.framework:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


Also, please add an executable jar of thingml-diversifier to the repository, so we can try your tool without building it.

Thanks
Mojtaba

**Comment by hernanponcedeleon** [comment]
Hi @brice-morin,

I managed to build all the maven projects but I'm facing some problem when running the scripts:
- generate_models: works ok
- generate_platform_code: I'm getting (between others) this:
```
-- GENERATING BASE MODEL CODE --
Running ThingML -c nodejs -s /home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/nodejs.thingml -o /home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-bytes-platform/nodejs/base
Checking for EMF errors and warnings
Generating code for configuration: test. InputDirectory is /home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs
Running Javascript for NodeJS compiler on configuration test [Mon Jul 16 13:13:11 CEST 2018]
Checking configuration...
Checking configuration... Done! Took 147 ms.
Error(s) in /home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/nodejs.thingml
	[line 19]: Property bytesSentCounter of Thing App is duplicated (possibly from an included thing).
	[line 71]: Property bytesSentCounter of Thing Client is duplicated (possibly from an included thing).
SUCCESS.
```
Even if there is a SUCCESS at the end, there are some errors before.
As far as I understand this is the step where having Arduino installed is necessary. What I have done is just downloading Arduino and run its installation script. Then I set
```
export ARDUINO_DIR=~/Downloads/arduino-1.8.5/
export ARDUINO_BUILDER_DIR=~/Downloads/arduino-1.8.5/
```
- run_generated_code: Between others, I get this error:
```
-- RUNNING BASE MODEL CODE --
rm: cannot remove '/home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-out/*': No such file or directory
run_generated_code.sh: line 60: npm: command not found
run_generated_code.sh: line 60: npm: command not found
run_generated_code.sh: line 60: npm: command not found
run_generated_code.sh: line 27: ./node_modules/webpack-cli/bin/webpack.js: No such file or directory
cp: cannot stat 'build/packed.js': No such file or directory
mv: cannot stat '/home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-out/binary': No such file or directory
!!! nodejs base 1 !!!
run_generated_code.sh: line 31: node: command not found
mv: cannot stat '/home/ponce/Downloads/thingml-diversifier-master/src/main/bash/bytes/../../../../target/thingml-out/output.log': No such file or directory

```
I also have some problems to run the jupyter scripts. I tried using jupiter from the browser. However I get an error when executing step 6 since obviously it does not recognize ../../../target/thingml-bytes-logs/nodejs/. I tried to load all the file there, but I also noticed that there are no logs. Probably because the previous script (run_generated_code) failed. 

Anyway it would be nice to have an easier way to run this in jupyter. I tried installing jupiter in my pc, but when I run it from the console (jupyter notebook) anyway it opens it in the web-browser and I have the same problem as if I run the browser version.

**Comment by hernanponcedeleon** [comment]
You are right, I was using the prototype from https://github.com/SINTEF-9012/thingml-diversifier.
However I still get some errors:
- generate_platform_code.sh:
```
---- LANGUAGE nodejs ----
-- GENERATING BASE MODEL CODE --
Running ThingML -c nodejs -s /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/nodejs.thingml -o /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-platform/nodejs/base
Checking for EMF errors and warnings
Generating code for configuration: test. InputDirectory is /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs
Running Javascript for NodeJS compiler on configuration test [Mon Jul 16 15:22:33 CEST 2018]
Checking configuration...
Checking configuration... Done! Took 137 ms.
Warnings(s) in /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/nodejs.thingml
	[line 5]: Property counter of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 6]: Property N of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 7]: Property bytesSentCounter of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 9]: Function rnd should return Byte. Found a value/expression that cannot be typed. Consider using a cast (<exp> as <type>).
	[line 74]: Property start is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 78]: Property _c is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 79]: Property _d is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 80]: Property _e is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 122]: Property duration is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
Compilation complete [Mon Jul 16 15:22:34 CEST 2018]. Took 21 ms.
SUCCESS.
-- GENERATING STATIC DIVERSIFICATED MODEL CODE --
Running ThingML -c nodejs -s /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/static/nodejs1.thingml -o /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-platform/nodejs/static/nodejs1
Checking for EMF errors and warnings
Generating code for configuration: test. InputDirectory is /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/static
Running Javascript for NodeJS compiler on configuration test [Mon Jul 16 15:22:35 CEST 2018]
Checking configuration...
Checking configuration... Done! Took 224 ms.
Warnings(s) in /home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-bytes-models/nodejs/static/nodejs1.thingml
	[line 20]: Property counter of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 21]: Property N of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 22]: Property bytesSentCounter of Thing Msgs is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 24]: Function rnd should return Byte. Found a value/expression that cannot be typed. Consider using a cast (<exp> as <type>).
	[line 32]: Message diversified.m1db is never sent
	[line 32]: Message diversified.m1cae is never sent
	[line 32]: Message diversified.m1db is never received
	[line 32]: Message diversified.m1cae is never received
	[line 82]: State INIT is a sink state. Consider making it final or use @ignore "sink"
	[line 83]: Property c of Thing App is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 85]: Property b of Thing App is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 123]: State INIT is a sink state. Consider making it final or use @ignore "sink"
	[line 127]: Property a of Thing App is never used. Consider removing (or using) it, or use @ignore "not-used".
	[line 188]: Property start is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 192]: Property _c is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 193]: Property _d is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 194]: Property _e is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 254]: Property duration is assigned with a value/expression which cannot be typed. Consider using a cast (<exp> as <Type>), or use @ignore "type-warning"
	[line 275]: State INIT is a sink state. Consider making it final or use @ignore "sink"
Compilation complete [Mon Jul 16 15:22:36 CEST 2018]. Took 45 ms.
SUCCESS.
```
Similar warnings follow. Not sure if the problems below are related to these warnings.
- run_generated_code.sh
```
---- LANGUAGE nodejs ----
-- RUNNING BASE MODEL CODE --
rm: cannot remove '/home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-out/*': No such file or directory
npm WARN deprecated state.js@5.11.1: Please use @steelbreeze/state

> memwatch-next@0.3.0 install /home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/memwatch-next
> node-gyp rebuild

make: Entering directory '/home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/memwatch-next/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
  CXX(target) Release/obj.target/memwatch/src/init.o
  CXX(target) Release/obj.target/memwatch/src/memwatch.o
../src/memwatch.cc: In function ‘void AsyncMemwatchAfter(uv_work_t*)’:
../src/memwatch.cc:128:35: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
                 g_cb->Call(3, argv);
                                   ^
In file included from ../src/memwatch.hh:9:0,
                 from ../src/memwatch.cc:6:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/memwatch.cc:203:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
             g_cb->Call(3, argv);
                               ^
In file included from ../src/memwatch.hh:9:0,
                 from ../src/memwatch.cc:6:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/memwatch/src/util.o
  SOLINK_MODULE(target) Release/obj.target/memwatch.node
  COPY Release/memwatch.node
make: Leaving directory '/home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/memwatch-next/build'
test@1.0.0 /home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out
├─┬ memwatch-next@0.3.0 
│ ├── bindings@1.3.0 
│ └── nan@2.10.0 
└── state.js@5.11.1 

▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine webpack@4.16.1: wanted: {"node":">=6.11.5"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:webpack-sources → ▄ ╢██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:webpack-sources → ▄ ╢██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine tapable@1.0.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine uglifyjs-webpack-plugin@1.2.7: wanted: {"node":">= 4.8 < 5.0.0 || >= 5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:webpack-sources → ▄ ╢██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:punycode → reques ▄ ╢███████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:urix → request    ▐ ╢██████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
test@1.0.0 /home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out
└── webpack@4.16.1  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine webpack-cli@3.0.8: wanted: {"node":">=6.11.5"} (current: {"node":"4.2.6","npm":"3.5.2"})
loadDep:yargs → request   ▌ ╢██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:yargs → get       ▄ ╢██████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
test@1.0.0 /home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out
├── webpack@4.16.1  extraneous
└── webpack-cli@3.0.8  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
/home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/webpack-cli/bin/cli.js:45
		return require("./prompt-command")(NON_COMPILATION_CMD, ...process.argv);
		                                                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
cp: cannot stat 'build/packed.js': No such file or directory
mv: cannot stat '/home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-out/binary': No such file or directory
!!! nodejs base 1 !!!
!!! nodejs base 2 !!!
!!! nodejs base 3 !!!
!!! nodejs base 4 !!!
!!! nodejs base 5 !!!
!!! nodejs base 6 !!!
!!! nodejs base 7 !!!
!!! nodejs base 8 !!!
!!! nodejs base 9 !!!
!!! nodejs base 10 !!!
-- RUNNING STATIC DIVERSIFICATED MODEL CODE --
!!! nodejs static 1 !!!
/home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/webpack-cli/bin/cli.js:45
		return require("./prompt-command")(NON_COMPILATION_CMD, ...process.argv);
		                                                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
cp: cannot stat 'build/packed.js': No such file or directory
mv: cannot stat '/home/ponce/Downloads/artifact-evaluation-master/morin/src/main/bash/bytes/../../../../target/thingml-out/binary': No such file or directory
!!! nodejs static 2 !!!
/home/ponce/Downloads/artifact-evaluation-master/morin/target/thingml-out/node_modules/webpack-cli/bin/cli.js:45
		return require("./prompt-command")(NON_COMPILATION_CMD, ...process.argv);

```
Similar errors (SyntaxError: Unexpected token ...) follow.

**Comment by brice-morin** [comment]
Warnings should not be a problem. I suspect it might be a problem with your node.js installation. Can you check that [node-gyp](https://github.com/nodejs/node-gyp) is properly installed?

> On windows (if you are using it...), please run the node-gyp install command in a terminal with administrator privileges: `npm install --global --production windows-build-tools`

BTW, which OS are you using?

Also, which version of Node.JS are you using (run `node -v`)? [The latest LTS version 8.11.3 should work fine](https://nodejs.org/en/)

**Comment by hernanponcedeleon** [comment]
I updated node.js and even if I still get several warning, it seems that all the files are generated.
I recommend that you add a sentence about having node.js and node-gyp installed (and which versions are needed).
I now reached the point where I managed to run jupyter script graphs.ipynb by installing runipy (this might be the easiest way to run such scripts). However when running images.ipynb I get the following error:
```
07/16/2018 04:26:27 PM INFO: Cell raised uncaught exception: 
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-8-c291f0b3b423> in <module>()
----> 1 plot_two_images(1, mask_nan(base_data), mask_nan(diversified_data))
      2 plt.savefig('picture_raw_bytes.png', dpi=300)

<ipython-input-7-c699a8c4b6a5> in plot_two_images(fignum, base_data, diversified_data)
     19     ax1.set_yticks([0,9])
     20     ax1.set_yticklabels(['1','10'])
---> 21     ax1.set_xticks(np.arange(0,base_data.shape[1], base_data.shape[1]/5))
     22     ax1.set_ylabel('Instance #')
     23     ax1.set_xlabel('Byte #')

ZeroDivisionError: division by zero
07/16/2018 04:26:27 PM INFO: Shutdown kernel
07/16/2018 04:26:28 PM WARNING: Exiting with nonzero exit status
```
I also get an error when running statistics.ipynb but I think is because the run_generated_code.sh script from src/main/bash/summary is still running. Is it normal that this takes so long?

**Comment by brice-morin** [comment]
OK, good progress. I will update the readme.

Yes, the summary part can take quite a long time (though we are still talking about minutes, not hours)

**Comment by brice-morin** [comment]
Also note that the `src/main/bash/summarty` step uses Node.JS and Go (but you can e.g. modify setup.sh to remove Go if you do not have/do not want Go installed). I updated the readme with sections about Node.Js installation and Go installation.

**Comment by moji1** [comment]
Hi @brice-morin 
Thanks for the reply. bin folder only includes a thingml.jar, could you please add thingml-diversifier.jar too?

Thanks
Moji

**Comment by brice-morin** [comment]
Hi @moji1 

Sorry, I thought I added it already... It should now be available

**Comment by moji1** [comment]
Hi @brice-morin 

I even have an issue with running the jar file you shared, can you please check the following error:

| ~/Desktop/artifactevaluation/artifact-evaluation/morin/src/main/bash/bytes @ Mojtabas-MBP-2 (mojtababagherzadeh) 
| => java -jar ../../../../bin/thingmldiversifier.jar ../../../../bin/HelloWorld.thingml 100 runtime ./thingml-diversifier 1
Exception in thread "main" java.lang.NoSuchFieldError: EOF_TOKEN
	at org.eclipse.xtext.parser.antlr.Lexer.nextToken(Lexer.java:59)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.BufferedTokenStream.fill(BufferedTokenStream.java:286)
	at org.antlr.runtime.BufferedTokenStream.toString(BufferedTokenStream.java:251)
	at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.parse(AbstractInternalAntlrParser.java:553)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:102)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.parse(AbstractAntlrParser.java:84)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:62)
	at org.eclipse.xtext.parser.AbstractParser.parse(AbstractParser.java:33)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:176)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:100)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.thingml.compilers.ThingMLCompiler.loadModel(ThingMLCompiler.java:147)
	at org.thingml.compilers.ThingMLCompiler.loadModel(ThingMLCompiler.java:134)
	at no.sintef.thingml.diversifier.Diversifier.main(Diversifier.java:60)
________________________________________________________
| ~/Desktop/artifactevaluation/artifact-evaluation/morin/src/main/bash/bytes @ Mojtabas-MBP-2 (mojtababagherzadeh) 

Note that I get the same error when I am trying to build the ThingML.

Thanks
Mojtaba

**Comment by hernanponcedeleon** [comment]
I tried to run run_generated_code.sh, but after 12 hs, the script is still running ...

**Comment by brice-morin** [comment]
Hi @moji1 

I suspect there is an issue with your input `HelloWorld.thingml`. You can try the samples we have included (which we use in the paper), like this: 

```
cd morin
java -jar bin/thingmldiversifier.jar src/main/resources/experiments/nodejs.thingml 100 runtime ./thingml-diversifier 1
```

**Comment by brice-morin** [comment]
@hernanponcedeleon do you have any outputs in the terminal?

**Comment by hernanponcedeleon** [comment]
@brice-morin no

**Comment by brice-morin** [comment]
@hernanponcedeleon are you trying both with Node.JS and Go (see `setup.sh`)? If so, do you have both node.js and Go installed?

**Comment by hernanponcedeleon** [comment]
I removed go from the setup file. Node.js is installed

**Comment by brice-morin** [comment]
hmmm... I was able to execute all the steps in `src/main/bash/summary` in 3 minutes with the default `setup.sh` with `N=10` and `LANGUAGES=(nodejs go)`

OK, just saw your comment. Yes, seems like a good idea to remove go.

**Comment by brice-morin** [comment]
@hernanponcedeleon Note that you will probably have to update this line in `statistics.ipynb`, so as to also remove go: `languages = ['nodejs', 'go']` (once you have been able to run the generated node.js)

**Comment by brice-morin** [comment]
@moji1 seems like a quite obscure XText/ANTLR issue... What OS and JDK are you using? Also, if you open the input thingml files in a text editor, can you check that they are properly terminated by an EndOfFile (EOF) special character?

**Comment by moji1** [comment]
I am using Mac os High Sierra 10.13.4 and my java version is 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by brice-morin** [comment]
Right... I must confess we have not tested our thingml-diversifier on Mac (and not ThingML neither, at least not recently). I do not have any Mac at hand, and it seems I cannot reproduce your stack trace on my PC, so I am a bit uncertain I will be able to fix this issue...

**Comment by moji1** [comment]
How about Linux? 

Also, can you please add a note in the documentation regarding the supported OS.

**Comment by brice-morin** [comment]
It should in principle work on Linux. I will test right now. Then I will update the readme accordingly with the supported OS

**Comment by hernanponcedeleon** [comment]
**Summary**

This artifact accompanies a paper presenting an MDE approach for the diversification of communicating systems based on abstraction, model transformation and code generation.
The approach generates high levels of diversity while keeping the overhead low.
The artifact consist of a tool and script to generate the figures of the paper.

**Assessment**

*Packaging: Exceeded expectations*

The tool is very easy to build using maven.
(\*) Additionally, the authors provide the tool as jar files which is very convenient for user not having maven installed.
The authors provide scripts to generate all the data (models, code, logs) for the experiment.
(\*) The authors also provide the generated models and source code in case the user have problem to run the tool. 
The above can be used to directly run the scripts generating the figures.

I give a "Exceeded expectations" mark because thanks to (\*), the artifact can be run even if one faces some problem in the intermediate steps.

*Reproducibility: Exceeded expectations*

The artifact provides several scripts to reproduce the results.
Even if the steps of building or running the tool fails, the results can still be reproduced since the artifact also contains the inputs for running the scripts (i.e. the tool per se and the data for generating he figures).

Since the tool for generating the diversified models takes several parameters as inputs (like number of diversified models, mode and random seed), the artifact allow to easily run different experiments.

The later is the reason I'm giving this artifact a "Exceeded expectations" mark.

*Documentation: Exceeded expectations*

The artifact is very well document with a step by step documentation on how to install and execute the artifact.

The only thing that was not documented (at least not at the level of detail of the other things) is how to run the jupyter scripts. In my case, it required some time to research about it and came up to the conclusion that installing runipy was the easiest solution.

It was also very helpful that the author was very active during the the review process, providing feedback and updating the documentation.

**Comment by moji1** [comment]
@brice-morin  
I could build and run the scripts after switching to Linux.

**Comment by brice-morin** [comment]
Ok, Very good :-)

**Comment by moji1** [comment]
Summary:
The artifact consists of thingml-diversifier and related scripts to evaluate the diversification overhead. 
thingml-diversifier accepts an abstract communication model described in ThingML and systemically diversifies the communication between different entities.

Documentation:
The documentation is clear and easy to follow. My only concern is adding a note regarding the supported OS. 

Easy to re-use:
It is easy to build the code and run the related scripts. Also, executable jar files are provided and users can use the artifact without building the code. To use the executable jar files instead of building code the `setup.sh` needs to be modified to point out to the jars files location correctly. 

Consistency with the paper:
The artifact is consistent with the paper.

Overall, the artifact is of high quality and I suggest its acceptance.

**Comment by grammarware** [comment]
Dear @brice-morin,

Based on all the comments and the reviews provided by the members of the Artifact Evaluation Committee of MoDELS 2018, we have reached the conclusion that this artifact conforms to the expectations and is hereby **approved**. Please use the [badge instructions](https://github.com/modelsconf2018/artifact-evaluation/blob/master/Badge.md) page to add the badge of approval to your article, and add the link to the ReMoDD entry with URI http://remodd.org/content/thingml-diversifier to the camera ready version of the paper.

Thank you very much for putting extra effort into the preparation and finalising of the artifact. If any of the comments above are still not addressed, please try to accommodate them before the conference.
